import React from 'react';

interface Props {
  section?: 'terms' | 'privacy' | 'refund' | 'return' | 'shipping';
}

const PAGE_TITLE = 'Terms, Privacy, Refund and Shipping Policies';

function SectionCard({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="rounded-2xl border border-amber-200 bg-white/95 p-5 sm:p-7 shadow-sm">
      <h2 className="text-xl sm:text-2xl font-bold text-stone-900">{title}</h2>
      <div className="mt-4 space-y-4 text-sm sm:text-[15px] leading-7 text-stone-700">{children}</div>
    </section>
  );
}

export const LegalPoliciesPage: React.FC<Props> = ({ section }) => {
  const activeSection = section || 'terms';

  React.useEffect(() => {
    document.title = PAGE_TITLE;
  }, []);

  React.useEffect(() => {
    const sectionId =
      activeSection === 'privacy'
        ? 'privacy-policy'
        : activeSection === 'refund'
          ? 'refund-cancellation-policy'
          : activeSection === 'return'
            ? 'return-policy'
            : activeSection === 'shipping'
              ? 'shipping-policy'
              : 'terms-and-conditions';

    const el = document.getElementById(sectionId);
    if (el) {
      setTimeout(() => {
        el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 40);
    }
  }, [activeSection]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-amber-50 via-yellow-50 to-stone-100 px-4 py-6 sm:px-8 sm:py-10">
      <div className="mx-auto max-w-5xl space-y-5">
        <header className="rounded-2xl border border-amber-300 bg-white p-5 sm:p-7 shadow-sm">
          <h1 className="text-2xl sm:text-3xl font-extrabold text-stone-900">Legal Policies</h1>
          <p className="mt-2 text-sm sm:text-base text-stone-600">
            This page is published for website verification and customer transparency purposes.
          </p>
          <div className="mt-4 flex flex-wrap gap-2 text-xs sm:text-sm">
            <a className="rounded-full border border-amber-300 bg-amber-100 px-3 py-1.5 font-semibold text-amber-900" href="#/terms-and-conditions">Terms</a>
            <a className="rounded-full border border-amber-300 bg-amber-100 px-3 py-1.5 font-semibold text-amber-900" href="#/privacy-policy">Privacy</a>
            <a className="rounded-full border border-amber-300 bg-amber-100 px-3 py-1.5 font-semibold text-amber-900" href="#/refund-cancellation-policy">Refund</a>
            <a className="rounded-full border border-amber-300 bg-amber-100 px-3 py-1.5 font-semibold text-amber-900" href="#/return-policy">Return</a>
            <a className="rounded-full border border-amber-300 bg-amber-100 px-3 py-1.5 font-semibold text-amber-900" href="#/shipping-policy">Shipping</a>
          </div>
        </header>

        <SectionCard id="terms-and-conditions" title="Terms and Conditions">
          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable,
            including amended provisions related to electronic records in various statutes. This electronic record is generated by a
            computer system and does not require physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules,
            2011, requiring publication of rules, regulations, privacy policy and terms of use for access or usage of
            ddminfotechnology.com, including related mobile site and mobile application (Platform).
          </p>
          <p>
            The Platform is owned by 9890000867, with registered office at SARAF LANE, GANJ BAZAAR, AHILYANAGAR
            (Platform Owner, we, us, our).
          </p>
          <p>
            By accessing or using the Platform, you agree to these Terms of Use and applicable policies. These terms may be modified at
            any time without prior notice. It is your responsibility to review updates periodically.
          </p>
          <p className="font-semibold text-stone-900">
            ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO THESE TERMS.
          </p>
          <ol className="list-decimal pl-5 space-y-2">
            <li>You agree to provide true, accurate and complete information and remain responsible for your account usage.</li>
            <li>We and third parties do not guarantee absolute accuracy, timeliness, performance, completeness or suitability of content.</li>
            <li>Your use of Platform and Services is at your own risk and discretion.</li>
            <li>Platform contents, design and graphics are proprietary and protected.</li>
            <li>Unauthorized use may result in legal action under applicable law.</li>
            <li>You agree to pay all charges associated with availing Services.</li>
            <li>You will not use Platform/Services for unlawful or prohibited purposes.</li>
            <li>Third-party links are governed by their own terms and privacy policies.</li>
            <li>Initiating a transaction creates a legally binding and enforceable contract for Services.</li>
            <li>You agree to indemnify Platform Owner and affiliates against claims resulting from breach, violations or infringements.</li>
            <li>Neither party is liable for delay or failure caused by force majeure events.</li>
            <li>These Terms are governed by laws of India.</li>
            <li>Disputes are subject to exclusive jurisdiction of competent courts in India.</li>
            <li>All concerns must be communicated using contact details published on this website.</li>
          </ol>
        </SectionCard>

        <SectionCard id="privacy-policy" title="Privacy Policy">
          <p>
            This Privacy Policy describes how 9890000867 and affiliates collect, use, share, protect and process personal data on
            ddminfotechnology.com (Platform). By visiting the Platform or availing products/services, you agree to this Policy, Terms
            of Use and applicable laws of India.
          </p>
          <h3 className="font-bold text-stone-900">Collection</h3>
          <p>
            We may collect personal details including name, date of birth, address, phone number, email, identity/address proof and,
            where applicable and with consent, payment information and biometric or physiological data for opted features.
          </p>
          <h3 className="font-bold text-stone-900">Usage</h3>
          <p>
            We use personal data to provide Services, process transactions, improve experience, resolve disputes, prevent fraud,
            communicate updates/offers, and enforce terms. Denial of required permissions may impact access to some services.
          </p>
          <h3 className="font-bold text-stone-900">Sharing</h3>
          <p>
            We may share data with group entities, affiliates, sellers, business partners, logistics partners, payment providers,
            government or law enforcement agencies where required by law or for fraud prevention and legal compliance.
          </p>
          <h3 className="font-bold text-stone-900">Security Precautions</h3>
          <p>
            We use reasonable security practices to protect information. However, internet transmission is not fully secure and carries
            inherent risks. Users must protect account credentials.
          </p>
          <h3 className="font-bold text-stone-900">Data Retention and Deletion</h3>
          <p>
            Users may request account deletion via profile/settings or contact support. Deletion may be delayed where grievances,
            claims, pending shipments or legal requirements exist. Data is retained only as long as needed under applicable law,
            and may be retained in anonymized form for analytics.
          </p>
          <h3 className="font-bold text-stone-900">Your Rights and Consent</h3>
          <p>
            You may access, rectify and update personal data through platform functionality. You may withdraw consent by writing to
            the Grievance Officer with subject: Withdrawal of consent for processing personal data.
          </p>
          <h3 className="font-bold text-stone-900">Policy Updates</h3>
          <p>
            This policy may be updated periodically. Significant changes may be notified as required under applicable laws.
          </p>
          <p>
            Grievance Officer contact details are available on this website. Support timings: Monday to Friday, 09:00 to 18:00.
          </p>
        </SectionCard>

        <SectionCard id="refund-cancellation-policy" title="Refund and Cancellation Policy">
          <ol className="list-decimal pl-5 space-y-2">
            <li>Cancellation requests are considered only if made within 1 day of placing the order.</li>
            <li>Cancellation may not be possible once shipment is initiated or the item is out for delivery.</li>
            <li>For perishable items (such as flowers/eatables), cancellation is generally not accepted.</li>
            <li>Damaged/defective items must be reported to customer service within 1 day of receipt.</li>
            <li>If product is not as shown/expected, report to customer service within 1 day of receipt.</li>
            <li>Warranty-related complaints for manufacturer warranty products must be referred to the manufacturer.</li>
            <li>Approved refunds are processed within 1 day.</li>
          </ol>
        </SectionCard>

        <SectionCard id="return-policy" title="Return Policy">
          <p>
            Refund/exchange is offered within 5 days of purchase. After 5 days, return/exchange/refund is not available.
          </p>
          <ol className="list-decimal pl-5 space-y-2">
            <li>Item must be unused, in original condition and with original packaging.</li>
            <li>Sale items may not be eligible for return/exchange.</li>
            <li>Replacement is offered for items found defective or damaged after verification.</li>
            <li>Some product categories may be exempt from return/refund and will be identified at purchase.</li>
            <li>Accepted return/exchange requests are processed after quality check at our end.</li>
          </ol>
        </SectionCard>

        <SectionCard id="shipping-policy" title="Shipping Policy">
          <p>
            Orders are shipped through registered domestic courier companies and/or speed post. Orders are typically shipped within
            5 days from order/payment date, or as per delivery timeline agreed at order confirmation.
          </p>
          <p>
            Platform Owner is not liable for delays by courier company or postal authority. Delivery is made to the address provided
            by the buyer at time of purchase and confirmation is sent to the registered email ID. Any shipping charge levied is
            non-refundable unless otherwise required by law.
          </p>
        </SectionCard>
      </div>
    </div>
  );
};

export default LegalPoliciesPage;
